quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.username=escritural
%dev.quarkus.datasource.password=escritural
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/escritural_event_lab

#Test
%test.quarkus.datasource.devservices.image-name=postgres:16-alpine

#Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-on-migrate=true

#ORM
quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true

#Kafka outgoing
%dev.kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.duplicata-events.connector=smallrye-kafka
mp.messaging.outgoing.duplicata-events.topic=duplicata-events
mp.messaging.outgoing.duplicata-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.duplicata-events.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

#Kafka incoming
mp.messaging.incoming.duplicata-events-in.connector=smallrye-kafka
mp.messaging.incoming.duplicata-events-in.topic=duplicata-events
mp.messaging.incoming.duplicata-events-in.group.id=invoice-notification-consumer
mp.messaging.incoming.duplicata-events-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.duplicata-events-in.value.deserializer=br.com.marco.escritural.adapters.in.messaging.InvoiceEventMessageDeserializer

#Kafka incoming DLQ
mp.messaging.incoming.duplicata-events-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.duplicata-events-in.dead-letter-queue.topic=duplicata-events-dlq
mp.messaging.incoming.duplicata-events-in.dead-letter-queue.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

#OpenAPI
quarkus.smallrye-openapi.info-title=Escritural Event Lab API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API de laboratório para o domínio simplificado de duplicata escritural.
